### ISSUE TITLE
add to FAQ page

### ISSUE THREAD

**Issue by sharlyngrace** [cathydeng/expunge.io#41]
We need to add something about how being found guilty in juvenile court is not a criminal conviction. What do you think about the text below?

Q: Is my juvenile record a criminal conviction?
A: No. In Illinois, you cannot be convicted of a crime in juvenile court. Juvenile court is separate from (adult) criminal court. Even if you were "found guilty" in juvenile court, that is not a criminal conviction, and you do not have to reveal it on job applications. If you think a job has seen your juvenile record, contact the Juvenile Expungement Help Desk at 312-229-6359.

**Comment by EvanHahn** [comment]
This appears to be done. Can we remove this issue? (Or, more likely: am I missing something?)
