### ISSUE TITLE
Step two bottom of page hidden

### ISSUE THREAD

**Issue by laurenancona** [cathydeng/expunge.io#50]
Need to add padding so link to next step is visible at bottom of page, currently social sharing overlay overlaps.
Browser: Chrome (Version 39.0.2171.71 (64-bit) on OSX Yosemite
![screen shot 2014-12-05 at 9 46 39 am](https://cloud.githubusercontent.com/assets/2152151/5317355/1c951856-7c64-11e4-880d-0598d0d98d5a.png)

**Comment by cathydeng** [comment]
thanks @laurenancona!
